import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "25-10-15-next-things-app-self",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div className="flex">
          <Sidebar />
          <main className="flex-1 m-4 text-3xl">{children}</main>
        </div>
      </body>
    </html>
  );
}
